### ISSUE TITLE
separate demos out into gfx-demos repo

### ISSUE THREAD

**Issue by ccmitchellusa** [dojo/gfx#8]

**Comment by wkeese** [comment]
This sounds like a bad idea.   If we start separating demos to separate repositories, we'll end up with twice the number of repositories, and we'll have to keep them in sync.

I know sometimes cordova users complain about having to remove unneeded code, but separating out the demos will hardly satisfy them, because they'll still need to remove the tests and documentation manually.

**Comment by ccmitchellusa** [comment]
The removal of demos will happen in the bower optimized build/package mirror, so agree. closing this ticket.

**Comment by cjolif** [comment]
I would still see advantages to demos being hosted separately like for example being able to rely on other packages that the library does not need to depend on (like gfx demos relying on dui while the gfx lib does not rely on dui). But I guess we can always decide that later when we will be at a point where demos are ready.
